
title: Nepthune

jekyll_auth:
  whitelist:
    - drafts?

include:
  - _pages
  - files
  - .htaccess
exclude:
  - script
  - bin
  - lib
  - Gemfile
  - Gemfile.lock
  - jekyll-auth.gemspec
  - jekyll-auth*.gem
  - config.ru
  - Rakefile
  - readme.md
  - vendor


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style