
title: Nepthune
url: nepthune-enpc.github.io


include:
  - _pages
  - files
  - .htaccess
  - assets
exclude:
  - script
  - bin
  - lib
  - Gemfile
  - Gemfile.lock
  - config.ru
  - Rakefile
  - readme.md
  - vendor
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Collections
collections:
  bourses:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: accueil
      permalink: /:path
  # _bourses
  - scope:
      path: ""
      type: bourses
    values:
      layout: bourse
      share: true
  


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 


# Outputting
permalink: /:categories/:title/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD


tsv_reader:
  converters:
    - all
  headers: true
 

# https://jekyllrb.com/tutorials/csv-to-table/