
title: Nepthune

include:
  - _pages
  - files
  - .htaccess
  - assets
exclude:
  - script
  - bin
  - lib
  - Gemfile
  - Gemfile.lock
  - config.ru
  - Rakefile
  - readme.md
  - vendor


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 